language: go
go:
  - 1.12.x
os:
  - linux
  
env:
  - GO111MODULE=on

install: skip

script:
  - go test ./action/...
  - go test ./operations/cleaning/...
  - go test ./operations/common/...
  - go test ./operations/image_processing/...
  - go test ./operations/math/...
  - go test ./operations/nlp/...
  - go test ./operations/restructuring/...
  - go test ./operations/string_processing/...
  - go test ./operations/utils/...
